### PR TITLE
update dependencies versions + txtRecord object structure changed

### LINKED ISSUE #5: Error: get key failed from google + TypeError: service.txtRecord.match
When trying to use this lib, I got this error
```
Error: get key failed from google
    at my_project/node_modules/node-googlehome/node_modules/google-tts-api/lib/key.js:23:23
```
It seems it's caused by the **google-tts-api** lib version;
I solved it locally by installing a fresher version via `npm install google-tts-api`
(so bumping it to 0.0.4 solved it.)

Then I had another issue in the search
```
TypeError: service.txtRecord.match is not a function
    at services.filter.service (my_project/node_modules/node-googlehome/lib/search.js:14:47)
```
I solved it by debugging and saw that the expected structure has changed (maybe?) the service.txtRecord is not a string but another object. One of those fields, `md` contained the searched `Google Home` string.
I cannot change it locally from my project, so I will send you a Pull Request for you to consider.

Thanks!

### PR DESCRIPTION
**Pull request by doppelganger9**
fixes #5

### CODE REVIEW

**Review by Zdrenka — APPROVED** [review]

**Comment by rtrompier** [comment]
Need merge and new version please :)

**Comment by doppelganger9** [comment]
Hi @rtrompier,
Are you asking me to bump the main `package.json` version as part of this PR? 🤔
As of the "merge" I don't get it, could you please explain what you expect (if you expect anything, that is 🤷‍♂️)
Thanks 😎

**Comment by rtrompier** [comment]
@ghostrick can you please merge this PR and push a new version to npm Thanks a lot.

@doppelganger9, mon message est pour l'admin du compte. J'ai également besoin de ce fix. Merci.

**Comment by ghostrick** [comment]
@doppelganger9 
i appreciate your PR :)

**Pull request merged**
